config/routes.rb
Stoverflow::Application.routes.draw do

  match '/' => 'questions#index'
  resources :questions

  resources :users, :only => [:new, :create, :show]
 
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content

  has_many :votes, :as => :votable
  belongs_to :user
  belongs_to :question

  validates :content, :presence => true

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :title, :content

  has_many :votes, :as => :votable
  has_many :answers
  belongs_to :user

  validates :title, :content, :presence => true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :handle, :email, :password

  has_many :votes
  has_many :questions
  has_many :answers

  validates :handle,   :presence => true
  validates :email,    :presence => true

  validates :handle, :uniqueness => true
  validates :email,  :uniqueness => true

  validates :handle,   :length => { :minimum => 6, :maximum => 15 }
  validates :password, :length => { :minimum => 6 }

  validates :handle, :format => { :with => /^[A-Za-z\d_]+$/}
  validates :email,  :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }
  validates :password, :format => { :with => /^[A-Za-z\d_]+$/}
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  # attr_accessible :value, :user, :votable
  
  belongs_to :votable, :polymorphic => true
  belongs_to :user

  validates :value, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params[:question])
    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes(params[:question])
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(params[:user])
    if user.save
      redirect_to users_path(@user.handle)
    else
      render :new
    end
  end

  def show
    @user = User.where(handle: params[:id]).first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stoverflow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_question_form.html.haml
= form_for @question do |f|
  .form-field
  = f.label :title
  %br
  = f.text_field :title 
  .form-field
  = f.label :content
  %br
  = f.text_area :content 
  .form-field=f.submit 'submit question

app/views/questions/edit.html.haml
= render :partial => "question_form"

app/views/questions/index.html.haml
%h1.header
  Welcome to the Questions Page!

- @questions.each do |question|
  %p
    Score:
    =question.votes.count
  %p=question.title.titleize  
  %p=question.content
  %p
    Written by 
    =question.user.handle.titleize
    Posted
    =time_ago_in_words(question.created_at)
    ago

  = link_to "Edit", edit_question_path(question)
  = link_to "Delete", question_path(question), :method => :delete

app/views/questions/new.html.haml
= render :partial => "question_form"

app/views/questions/show.html.haml
= @question.title
%br
= @question.content

app/views/users/new.html.haml
%h2 Sign Up For Stoverflow

= form_for @user do |f|
  = f.label(:username)
  = f.text_field(:handle, placeholder: 'eg. braveLittleToaster')

  = f.label(:email)
  = f.text_field(:email, placeholder: 'eg. toaster@email.com')
  
  = f.label(:password)
  = f.text_field(:password, placeholder: 'eg. t0ast3d')
  = f.submit('Sign Up')

app/views/users/show.html.haml
%h2= @user.handle
%h4= @user.email